Repository hpc/charliecloud, pull requests merged in 2018-11, with the labels that each got.

#281 add /usr/sbin to is_bin function
  bin/ch-fromhost
  doc-src/ch-fromhost_desc.rst
Labels: bug, ready to merge

#283 remove shebang from base.sh (closes #282)
  bin/base.sh
Labels: ready to merge

#288 refactor tests & examples to use context directory .
  doc-src/dev.rst
  doc-src/faq.rst
  doc-src/tutorial.rst
  examples/mpi/lammps/Dockerfile
  examples/mpi/mpibench-mpich/test.bash
  examples/mpi/mpibench-mpich/test.bats
  examples/mpi/mpibench/Dockerfile.mpich
  examples/mpi/mpibench/Dockerfile.openmpi
  examples/mpi/mpibench/test.bash
  examples/mpi/mpibench/test.bats
  examples/mpi/mpihello-mpich/test.bash
  examples/mpi/mpihello-mpich/test.bats
  examples/mpi/mpihello/Dockerfile.mpich
  examples/mpi/mpihello/Dockerfile.openmpi
  examples/mpi/mpihello/test.bash
  examples/mpi/mpihello/test.bats
  examples/serial/hello/Dockerfile
  test/Makefile
  test/README
  test/common.bash
  test/make-auto
Labels: enhancement

#296 vagrant: update disk resizing for CentOS base box v1809.01
  packaging/vagrant/Vagrantfile
Labels: ready to merge

#293 remove documentation from rpm build (closes #244)
  packaging/redhat/charliecloud.spec
Labels: ready to merge

#290 add injected nvidia files to fromhost clean
  test/run/ch-fromhost.bats
Labels: ready to merge
