Repository hpc/charliecloud, pull requests merged in 2019-07, with the labels that each got.

#462 Add missing CFLAGS, CPPFLAGS and LDFLAGS for some examples/tests
  examples/syscalls/Makefile
  test/Makefile
Labels: bug, ready to merge

#478 Makefile: Allow to override DOCDIR.
  Makefile
Labels: enhancement

#480 test/docs-sane: fix for Python 3
  test/docs-sane
Labels: ready to merge

#431 OCI shim for ch-run
  bin/base.sh
  bin/ch-build
  bin/ch-builder2tar
  bin/ch-run-oci
  bin/ch-run.c
  doc-src/ch-build_desc.rst
  doc-src/ch-builder2tar_desc.rst
  doc-src/ch-grow_desc.rst
  doc-src/ch-run-oci.rst
  doc-src/ch-run-oci_desc.rst
  doc-src/charliecloud.rst
  doc-src/command-usage.rst
  doc-src/conf.py
  doc-src/dev.rst
  doc-src/install.rst
  test/Build.buildah
  test/Dockerfile.centos7
  test/Dockerfile.exhaustive
  test/build.bats
  test/chtest/Build
  test/common.bash
  test/docs-sane
  test/run_first.bats
  test/travis-before.bash
  test/travis-install.bash
  test/travis.bash
  test/travis.yml
Labels: ready to merge

#459 add ch-checkns (namespace sanity check)
  .gitignore
  Makefile
  bin/Makefile
  bin/ch-checkns.c
  bin/charliecloud.c
  doc-src/ch-checkns.rst
  doc-src/ch-checkns_desc.rst
  doc-src/charliecloud.rst
  doc-src/command-usage.rst
  doc-src/conf.py
  examples/syscalls/Makefile
  examples/syscalls/userns.c
  packaging/vagrant/Vagrantfile
  test/run_first.bats
Labels: ready to merge

#483 fully unprivileged Buildah
  README.rst
  bin/base.sh
  bin/ch-build
  doc-src/ch-build_desc.rst
  doc-src/install.rst
  test/travis-install.bash
  test/travis.yml
Labels: ready to merge

#487 test suite: $CH_BUILDER should affect test-build only
  examples/mpi/paraview/test.bats
  test/common.bash
  test/make-auto
  test/make-auto.d/build_custom.bats.in
  test/make-auto.d/build_docker.bats.in
  test/make-auto.d/docker_to_archive.bats.in
  test/make-auto.d/pull_docker.bats.in
  test/make-auto.d/run_image.bats.in
  test/make-auto.d/unpack.bats.in
Labels: bug

#453 separate test make install
  Makefile
  packaging/fedora/charliecloud.spec
  test/Makefile
Labels: ready to merge

#481 Fix hardcoded calls to gcc.
  test/Makefile
Labels: bug, ready to merge

#491 Fix Vagrantfile to reflect change in charliecloud test location
  packaging/vagrant/Vagrantfile
Labels: bug, ready to merge
