Repository hpc/charliecloud, pull requests merged in 2019-06, with the labels that each got.

#433 change broken images test
  test/run/ch-run_misc.bats
Labels: ready to merge

#448 update libexecdir and doc paths to use charliecloud-version
  Makefile
  packaging/fedora/charliecloud.spec
  test/run/build-rpms.bats
  test/travis.sh
Labels: ready to merge

#450 tests: test host launch of OpenMPI on ARM
  README.rst
  examples/mpi/lammps/Dockerfile
  examples/mpi/lammps/test.bats
  examples/mpi/mpibench/test.bats
  examples/mpi/mpihello/test.bats
  examples/mpi/paraview/Dockerfile
  examples/mpi/paraview/test.bats
  test/Dockerfile.openmpi
  test/common.bash
Labels: ready to merge

#457 check man page sanity
  bin/ch-build2dir
  bin/ch-pull2dir
  bin/ch-pull2tar
  bin/ch-tar2dir
  doc-src/charliecloud.rst
  doc-src/command-usage.rst
  doc-src/conf.py
  packaging/fedora/charliecloud.spec
  test/build.bats
  test/docs-sane
Labels: ready to merge

#461 Openmpi examples: resolve issues with Dockerfile
  test/Dockerfile.openmpi
Labels: bug, ready to merge

#408 squashfs: add helper scripts and tests
  README.rst
  bin/base.sh
  bin/ch-dir2squash
  bin/ch-docker2squash
  bin/ch-docker2tar
  bin/ch-mount
  bin/ch-tar2dir
  bin/ch-tar2squash
  bin/ch-umount
  doc-src/ch-dir2squash.rst
  doc-src/ch-dir2squash_desc.rst
  doc-src/ch-docker2squash.rst
  doc-src/ch-docker2squash_desc.rst
  doc-src/ch-docker2tar_desc.rst
  doc-src/ch-mount.rst
  doc-src/ch-mount_desc.rst
  doc-src/ch-tar2squash.rst
  doc-src/ch-tar2squash_desc.rst
  doc-src/ch-umount.rst
  doc-src/ch-umount_desc.rst
  doc-src/charliecloud.rst
  doc-src/command-usage.rst
  doc-src/conf.py
  doc-src/install.rst
  test/build_post.bats
  test/common.bash
  test/make-auto
  test/make-auto.d/build_custom.bats.in
  test/make-auto.d/build_docker.bats.in
  test/make-auto.d/docker_to_archive.bats.in
  test/make-auto.d/pull_docker.bats.in
  test/make-auto.d/run_image.bats.in
  test/make-auto.d/unpack.bats.in
  test/run_first.bats
  test/travis.yml
Labels: enhancement

#455 new internal builder "ch-grow"
  Makefile
  bin/base.sh
  bin/ch-build
  bin/ch-build2dir
  bin/ch-builder2tar
  bin/ch-docker2squash
  bin/ch-docker2tar
  bin/ch-grow
  bin/ch-pull2tar
  bin/ch-run.c
  bin/charliecloud.c
  bin/charliecloud.h
  doc-src/ch-build2dir_desc.rst
  doc-src/ch-build_desc.rst
  doc-src/ch-builder2tar.rst
  doc-src/ch-builder2tar_desc.rst
  doc-src/ch-grow.rst
  doc-src/ch-grow_desc.rst
  doc-src/ch-pull2tar_desc.rst
  doc-src/ch-run_desc.rst
  doc-src/ch-tar2dir_desc.rst
  doc-src/charliecloud.rst
  doc-src/command-usage.rst
  doc-src/conf.py
  doc-src/dev.rst
  doc-src/faq.rst
  doc-src/install.rst
  doc-src/test.rst
  doc-src/tutorial.rst
  doc-src/vm.rst
  examples/mpi/mpibench/test.sh
  examples/mpi/paraview/Dockerfile
  examples/mpi/paraview/test.bats
  test/Dockerfile.centos7
  test/Dockerfile.exhaustive
  test/Dockerfile.mpich
  test/Dockerfile.nvidia
  test/Makefile
  test/build.bats
  test/build_post.bats
  test/common.bash
  test/make-auto
  test/make-auto.d/build_custom.bats.in
  test/make-auto.d/build_docker.bats.in
  test/make-auto.d/docker_to_archive.bats.in
  test/make-auto.d/pull_docker.bats.in
  test/make-auto.d/run_image.bats.in
  test/make-auto.d/unpack.bats.in
  test/run/ch-run_misc.bats
  test/travis.sh
  test/travis.yml
Labels: enhancement

#464 Added Nixos package into install doc
  doc-src/install.rst
Labels: enhancement
