Repository hpc/charliecloud, pull requests merged in 2019-05, with the labels that each got.

#421 test/chtest/printns: reimplement in Python
  test/chtest/printns
  test/run/ch-run_join.bats
Labels: ready to merge

#427 ch-tar2dir: remove --verbose because it's b0rken
  bin/ch-tar2dir
  doc-src/ch-tar2dir_desc.rst
Labels: ready to merge

#439 test/Build.buildah: update to latest Buildah and runc
  test/Build.buildah
  test/travis.yml
Labels: ready to merge

#436 examples: update mesa within paraview example
  examples/mpi/paraview/Dockerfile
Labels: bug, ready to merge

#437 OpenMPI examples: downgrade libpsm2, libibverbs, UCX
  test/Dockerfile.openmpi
Labels: bug, ready to merge

#424 rm Cray note now that the relevant CLE versions are old
  README.rst
  doc-src/install.rst
Labels: ready to merge

#385 RPM build improvements
  doc-src/dev.rst
  doc-src/test.rst
  packaging/fedora/build
  packaging/fedora/charliecloud.rpmlintrc
  packaging/fedora/charliecloud.spec
  test/Dockerfile.centos7
  test/README.md
  test/run/build-rpms.bats
Labels: enhancement, ready to merge

#438 tests: test guest launch of OpenMPI on ARM
  examples/mpi/lammps/Dockerfile
  examples/mpi/lammps/test.bats
  examples/mpi/mpibench/Dockerfile.openmpi
  examples/mpi/mpibench/test.bats
  examples/mpi/mpihello/Dockerfile.openmpi
  examples/mpi/mpihello/test.bats
  examples/mpi/paraview/Dockerfile
  examples/mpi/paraview/test.bats
  test/Dockerfile.openmpi
Labels: ready to merge

#443 documentation updates for openSUSE and SUSE
  doc-src/install.rst
  packaging/opensuse/README
Labels: ready to merge
