Repository hpc/charliecloud, pull requests merged in 2019-08, with the labels that each got.

#502 handle ARG instruction in Dockerfile
  bin/ch-build
  bin/ch-grow
  doc-src/ch-grow_desc.rst
  test/Dockerfile.argenv
  test/Dockerfile.debian9
  test/Dockerfile.exhaustive
  test/build_post.bats
  test/run/ch-run_misc.bats
Labels: enhancement, ready to merge

#496 better error message if we find "lark" instead of "lark-parser"
  bin/ch-grow
Labels: enhancement, ready to merge?

#523 fix looping install bug on systems without python
  Makefile
Labels: ready to merge?

#516 skip test "root with non-zero gid refused" if sudo not configured
  test/run/ch-run_escalated.bats
Labels: ready to merge?

#515 make /etc/{hosts,resolv.conf} bind-mounts optional
  bin/charliecloud.c
  test/run/ch-run_misc.bats
Labels: ready to merge?

#513 Add error handling for no ch-run case
  bin/ch-grow
Labels: ready to merge?
