Repository hpc/charliecloud, pull requests merged in 2019-10, with the labels that each got.

#557 alphabetize functions in common.bash
  test/common.bash
Labels: enhancement

#530 Update vagrant default
  doc-src/vm.rst
  packaging/vagrant/Vagrantfile
Labels: ready to merge?

#545 Builder2squash fixes
  bin/base.sh
  bin/ch-builder2squash
  bin/ch-builder2tar
Labels: ready to merge?

#546 HSN bandwidth test: Don't run on single node; clean up
  examples/mpi/mpibench/test.bats
  test/common.bash
Labels: bug, ready to merge?

#547 freshen Spack example
  examples/serial/spack/Dockerfile
Labels: enhancement

#564 Update LAMMPS image and test mpi4py with LAMMPS example.
  examples/mpi/lammps/Dockerfile
  examples/mpi/lammps/simple.patch
  examples/mpi/lammps/test.bats
Labels: enhancement, ready to merge?

#570 ch-run-oci: check multiple paths for inferred bundles
  bin/ch-run-oci
Labels: ready to merge?

#573 reset terminal colors even if we crash
  bin/ch-grow
Labels: ready to merge?

#528 executables show help if no arguments
  bin/base.sh
  bin/ch-checkns.c
  bin/ch-grow
  bin/ch-pull2dir
  bin/ch-pull2tar
  bin/ch-run-oci
  bin/ch-run.c
  bin/ch-ssh.c
  test/build.bats
Labels: ready to merge?

#447 new feature: ch-test
  Makefile
  bin/base.sh
  bin/ch-test
  doc-src/ch-test.rst
  doc-src/ch-test_desc.rst
  doc-src/charliecloud.rst
  doc-src/command-usage.rst
  doc-src/conf.py
  doc-src/index.rst
  doc-src/test.rst
  doc-src/vm.rst
  test/Makefile
  test/build.bats
  test/common.bash
  test/make-perms-test
  test/run/ch-run_uidgid.bats
  test/run_first.bats
  test/travis-before.bash
  test/travis-install.bash
  test/travis.bash
  test/travis.yml
Labels: ready to merge?
