Repository hpc/charliecloud, pull requests merged in 2020-04, with the labels that each got.

#709 ch-grow: fix parsing bugs
  bin/ch-grow.py.in
  lib/charliecloud.py
Labels: bug

#708 shell scripts: remove unneeded parentheses
  bin/ch-test
  bin/ch-umount
  examples/chtest/Build
  lib/base.sh
  test/Build.skopeo-umoci
  test/common.bash
  test/travis.bash
Labels: ready to merge?

#712 Add all parameter to Vagrantfile
  packaging/vagrant/Vagrantfile
Labels: ready to merge?

#710 docs: correct example path in tutorial
  doc/tutorial.rst
Labels: bug

#705 test COPY and implement "correct" behavior in ch-grow
  .gitignore
  bin/ch-grow.py.in
  doc/ch-grow_desc.rst
  doc/faq.rst
  examples/Makefile.am
  examples/copy/Dockerfile
  examples/copy/dirA/fileAa
  examples/copy/dirB/fileBa
  examples/copy/dirB/fileBb
  examples/copy/dirCa/dirCb/fileCba
  examples/copy/dirCa/dirCb/fileCbb
  examples/copy/dirD/fileDa
  examples/copy/dirEa/dirEb/fileEba
  examples/copy/dirEa/dirEb/fileEbb
  examples/copy/fileA
  examples/copy/fileB
  examples/copy/test.bats
  test/Makefile.am
  test/build/50_dockerfile.bats
  test/fixtures/README
Labels: ready to merge?

#714 configure: be more clear that non-Linux is unsupported
  configure.ac
Labels: bug, ready to merge?

#722 build: don't create bogus symlinks when make is run twice
  examples/Makefile.am
Labels: bug, ready to merge?

#723 ch-test: add 'all' phase to usage output
  bin/ch-test
Labels: bug

#724 Remove skopeo and umoci
  doc/faq.rst
  packaging/fedora/charliecloud.spec
  packaging/vagrant/Vagrantfile
  test/Build.skopeo-umoci
  test/Makefile.am
  test/travis-install.bash
Labels: ready to merge?

#728 tidy C code
  bin/ch-run.c
  bin/ch_core.h
  bin/ch_misc.c
  bin/ch_misc.h
Labels: ready to merge?
