Repository hpc/charliecloud, pull requests merged in 2020-12, with the labels that each got.

#912 change CI from Travis to GitHub Actions
  .github/README
  .github/workflows/main.yml
  .travis.yml
  Makefile.am
  bin/ch-test
  configure.ac
  doc/dev.rst
  misc/grep
  packaging/fedora/build
  test/Makefile.am
  test/build/50_pull.bats
  test/common.bash
  test/travis-before.bash
  test/travis-install.bash
  test/travis.bash
  test/travis.yml
Labels: enhancement, ready to merge?

#919 restore correct README
  .github/PERUSEME
  Makefile.am
Labels: bug

#910 Ignore leading and trailing spaces in Sphinx shebang
  configure.ac
Labels: ready to merge?

#917 ch-fromhost: clarify docs
  bin/ch-fromhost
  doc/ch-fromhost_desc.rst
  doc/command-usage.rst
  doc/conf.py
Labels: ready to merge?

#911 refactor fakeroot
  bin/ch-grow.py.in
  doc/ch-grow_desc.rst
  examples/Dockerfile.centos7
  examples/Dockerfile.centos8
  lib/build.py
  lib/charliecloud.py
  lib/fakeroot.py
  test/Dockerfile.fakeroot
  test/Makefile.am
  test/build/50_fakeroot.bats
  test/make-auto.d/build.bats.in
Labels: ready to merge?

#904 rename ch-grow to ch-image
  .github/workflows/main.yml
  .gitignore
  bin/Makefile.am
  bin/ch-build
  bin/ch-builder2tar
  bin/ch-grow.py.in
  bin/ch-image.py.in
  bin/ch-test
  configure.ac
  doc/Makefile.am
  doc/ch-build_desc.rst
  doc/ch-grow_desc.rst
  doc/ch-image.rst
  doc/ch-image_desc.rst
  doc/charliecloud.rst
  doc/command-usage.rst
  doc/conf.py
  doc/faq.rst
  doc/install.rst
  examples/Dockerfile.nvidia
  examples/exhaustive/Dockerfile
  examples/paraview/Dockerfile
  lib/base.sh
  lib/build.py
  lib/charliecloud.py
  lib/fakeroot.py
  packaging/fedora/lib64.patch
  packaging/vagrant/Vagrantfile
  test/.dockerignore
  test/Makefile.am
  test/build/50_ch-image.bats
  test/build/50_dockerfile.bats
  test/build/50_fakeroot.bats
  test/build/50_pull.bats
  test/build/99_cleanup.bats
  test/common.bash
  test/docs-sane.py.in
  test/make-auto.d/build.bats.in
Labels: ready to merge?

#924 ch-image: rename CH_GROW_STORAGE to CH_IMAGE_STORAGE
  bin/ch-image.py.in
  bin/ch-test
  doc/ch-image_desc.rst
  lib/charliecloud.py
  test/build/50_ch-image.bats
  test/build/50_fakeroot.bats
  test/common.bash
Labels: enhancement, ready to merge?

#925 test suite: demote Spark from standard to full scope
  examples/spark/Dockerfile
Labels: enhancement, ready to merge?

#922 ch-grow pull: update resolving whiteouts
  lib/charliecloud.py
Labels: ready to merge?

#927 configure: reports for documentation
  .github/workflows/main.yml
  README.rst
  configure.ac
Labels: ready to merge?

#937 configure: fix pack image builder to tar
  configure.ac
Labels: ready to merge?

#888 examples: enable building more examples with ch-image
  examples/Dockerfile.nvidia
  examples/paraview/Dockerfile
  lib/fakeroot.py
  test/build/50_fakeroot.bats
Labels: ready to merge?
