Repository hpc/charliecloud, pull requests merged in 2020-05, with the labels that each got.

#727 constify
  bin/ch-checkns.c
  bin/ch_core.c
  bin/ch_core.h
  bin/ch_misc.c
  bin/ch_misc.h
  doc/dev.rst
Labels: ready to merge?

#742 Skip lustre example image
  examples/lustre/Dockerfile
Labels: bug

#743 ch-test: don't fail silently if path components missing
  doc/ch-test_desc.rst
  test/common.bash
Labels: ready to merge?

#736 add username to default ch-grow storage
  bin/ch-grow.py.in
  bin/ch-test
  bin/ch-tug.py.in
  doc/ch-grow_desc.rst
  doc/ch-tug_desc.rst
  lib/charliecloud.py
Labels: enhancement, ready to merge?

#745 fix example bugs
  examples/obspy/test.bats
  examples/spack/test.bats
Labels: bug
