Repository hpc/charliecloud, pull requests merged in 2020-08, with the labels that each got.

#816 Support versions of oci spec up to 1.0.∞
  bin/ch-run-oci.py.in
Labels: ready to merge?

#796 Add --list option to ch-grow
  bin/ch-grow.py.in
  lib/charliecloud.py
  test/build/50_misc.bats
Labels: ready to merge?

#817 tests: add ln -T for consistency with examples
  test/Makefile.am
Labels: bug, ready to merge?

#826 ch-grow/ch-tug: fix symlink handling
  lib/charliecloud.py
  test/Dockerfile.symlink
  test/build/50_ch-tug.bats
Labels: ready to merge?

#809 test form of version number but not value
  doc/faq.rst
  packaging/fedora/lib64.patch
  test/build/10_sanity.bats
Labels: enhancement, ready to merge?

#831 clean up error handling in Python code
  bin/ch-grow.py.in
  bin/ch-run-oci.py.in
  bin/ch-tug.py.in
  doc/Makefile.am
  doc/ch-grow_desc.rst
  doc/ch-run-oci_desc.rst
  doc/ch-tug_desc.rst
  doc/conf.py
  doc/py_env.rst
  lib/charliecloud.py
  packaging/fedora/lib64.patch
Labels: ready to merge?

#834 docs: fix searching
  doc/Makefile.am
  doc/install.rst
Labels: ready to merge?
