Repository hpc/charliecloud, pull requests merged in 2020-07, with the labels that each got.

#800 add custom check for asprintf(3)
  configure.ac
Labels: ready to merge?

#797 clean up Python module version dependencies
  bin/ch-grow.py.in
  configure.ac
Labels: enhancement, ready to merge?

#807 examples: bump Spark version
  examples/spark/Dockerfile
Labels: bug, ready to merge?

#805 ch-pull2dir: tidy use of sed
  bin/ch-pull2dir
Labels: bug, ready to merge?

#808 configure: add --enable-buggy-build to omit -Werror
  configure.ac
  doc/install.rst
Labels: enhancement, ready to merge?

#795 ch-grow: print warnings about unsupported features
  bin/ch-grow.py.in
  examples/Makefile.am
  examples/exhaustive/Dockerfile
  examples/exhaustive/test.bats
  lib/charliecloud.py
  packaging/fedora/build
  packaging/fedora/charliecloud.rpmlintrc
  test/.dockerignore
  test/Makefile.am
  test/build/50_dockerfile.bats
  test/fixtures/README
  test/fixtures/empty-file
Labels: ready to merge?
