Repository hpc/charliecloud, pull requests merged in 2020-01, with the labels that each got.

#613 add docker requirement for docker pull tests
  test/Build.ch-pull2dir
  test/Build.ch-pull2tar
Labels: bug

#615 add cython to lammps
  examples/lammps/Dockerfile
Labels: ready to merge?

#612 clean up shell script lint
  autogen.sh
  bin/ch-test
  doc/make-deps-overview
  libexec/Makefile.am
  libexec/base.sh
  misc/grep
  test/Build.centos7xz
  test/Build.ch-pull2dir
  test/Build.ch-pull2tar
  test/Build.docker_pull
  test/Build.skopeo-umoci
  test/build.bats
  test/chtest-make-auto
Labels: ready to merge?

#624 make docs build with old Sphinx
  configure.ac
  doc/Makefile.am
  doc/conf.py
  doc/dev.rst
Labels: ready to merge?

#618 restore script to publish web docs
  doc/Makefile.am
  doc/dev.rst
  doc/install.rst
  doc/publish
Labels: ready to merge?

#625 Modify autogen.sh to use autoreconf --force --install
  autogen.sh
Labels: ready to merge?

#626 ch-test: validate version number consistency
  bin/ch-test
  doc/dev.rst
Labels: ready to merge?

#628 Vagrantfile: update to work with new Autotools build
  packaging/vagrant/Vagrantfile
Labels: bug

#631 Travis: don't run for non-master branches
  test/travis.yml
Labels: enhancement, ready to merge?
