Repository hpc/charliecloud, pull requests merged in 2020-02, with the labels that each got.

#630 ch-test: add pedantic mode
  .gitignore
  bin/ch-test
  doc/ch-test_desc.rst
  examples/mpibench/test.bats
  examples/spark/test.bats
  libexec/Makefile.am
  test/build.bats
  test/common.bash
  test/run/build-rpms.bats
  test/run/ch-run_escalated.bats
  test/run/ch-run_isolation.bats
  test/run/ch-run_uidgid.bats
  test/travis-install.bash
Labels: enhancement, ready to merge?

#640 Bump Spark version to resolve build error
  examples/spark/Dockerfile
Labels: bug

#632 ch-test: accept long options with arg separated by equals
  bin/ch-test
Labels: enhancement, ready to merge?

#642 fix tests for Buster
  test/run/ch-run_misc.bats
Labels: bug, ready to merge?

#647 docs: fix typos
  doc/ch-fromhost_desc.rst
  doc/ch-grow_desc.rst
Labels: bug

#656 ch-test: change version mismatch from error to warning
  bin/ch-test
Labels: bug, ready to merge?

#659 autotools: add --with-sphinx-python, better docs
  autogen.sh
  configure.ac
  doc/install.rst
Labels: ready to merge?

#644 ch-test: fix silent do-nothing with e-mail problems
  bin/ch-test
Labels: bug, ready to merge?

#667 doc: fix parallel build
  doc/Makefile.am
Labels: ready to merge?

#616 add python base image pulling tool
  .gitignore
  bin/Makefile.am
  bin/ch-grow.py.in
  bin/ch-tug.py.in
  configure.ac
  doc/Makefile.am
  doc/ch-grow_desc.rst
  doc/ch-tug.rst
  doc/ch-tug_desc.rst
  doc/charliecloud.rst
  doc/command-usage.rst
  doc/conf.py
  doc/faq.rst
  doc/install.rst
  libexec/Makefile.am
  libexec/charliecloud.py
  test/build.bats
  test/travis-install.bash
  test/whiteout
Labels: ready to merge?

#666 add missing files to tarballs
  Makefile.am
  bin/Makefile.am
  doc/Makefile.am
Labels: ready to merge?

#623 Add Lustre tests through LFS
  bin/ch-test
  doc/ch-test_desc.rst
  examples/Makefile.am
  examples/lustre/Dockerfile
  examples/lustre/test.bats
Labels: ready to merge?
