Repository hpc/charliecloud, pull requests merged in 2020-09, with the labels that each got.

#835 multi-stage build
  bin/ch-grow.py.in
  examples/Makefile.am
  examples/multistage/Dockerfile
  examples/multistage/test.bats
  test/build/50_dockerfile.bats
Labels: ready to merge?

#848 ENV: accept line continuations
  bin/ch-build
  examples/exhaustive/Dockerfile
  examples/spark/Dockerfile
  lib/charliecloud.py
  test/Dockerfile.argenv
  test/build/50_dockerfile.bats
Labels: bug, ready to merge?

#842 ch-grow: add subcommands and merge ch-tug
  .gitignore
  bin/Makefile.am
  bin/ch-build
  bin/ch-builder2tar
  bin/ch-grow.py.in
  bin/ch-run-oci.py.in
  bin/ch-tug.py.in
  configure.ac
  doc/Makefile.am
  doc/ch-grow_desc.rst
  doc/ch-tug.rst
  doc/ch-tug_desc.rst
  doc/charliecloud.rst
  doc/command-usage.rst
  doc/conf.py
  doc/faq.rst
  doc/install.rst
  lib/Makefile.am
  lib/build.py
  lib/charliecloud.py
  lib/misc.py
  packaging/fedora/charliecloud.spec
  packaging/fedora/lib64.patch
  test/Makefile.am
  test/build/50_ch-grow.bats
  test/build/50_dockerfile.bats
  test/build/50_misc.bats
  test/build/50_pull.bats
Labels: enhancement, ready to merge?

#851 ch-run: add $CH_RUNNING
  bin/ch-run.c
  doc/ch-run_desc.rst
  test/run/ch-run_misc.bats
Labels: ready to merge?

#845 Vagrantfile: enable gettys
  packaging/vagrant/Vagrantfile
  test/run/ch-run_uidgid.bats
Labels: ready to merge?

#855 configure: correct nvidia configure check to use NVIDIA_CLI consistently
  configure.ac
Labels: ready to merge?
