Repository hpc/charliecloud, pull requests merged in 2020-03, with the labels that each got.

#676 examples/lustre: add missing variable, fix example grouping
  bin/ch-test
  doc/ch-test_desc.rst
  examples/lustre/test.bats
Labels: bug

#680 remove /bin/true from run phase testing
  bin/ch-test
  test/Makefile.am
  test/make-auto.d/run_image.bats.in
  test/make-auto.d/unpack.bats.in
Labels: ready to merge?

#671 ch-tar2squash: remove
  bin/Makefile.am
  bin/ch-tar2squash
  doc/Makefile.am
  doc/ch-tar2squash.rst
  doc/ch-tar2squash_desc.rst
  doc/charliecloud.rst
  doc/command-usage.rst
  doc/conf.py
Labels: enhancement

#634 add variable to force tar over squashfs during tests
  bin/ch-test
  configure.ac
  doc/ch-test_desc.rst
  libexec/base.sh
  test/common.bash
  test/make-auto.d/builder_to_archive.bats.in
  test/travis-install.bash
  test/travis.yml
Labels: ready to merge?

#688 don't try to build docs if RTD theme is missing
  configure.ac
Labels: bug

#685 move libraries from libexec to lib
  .gitignore
  Makefile.am
  bin/ch-build
  bin/ch-build2dir
  bin/ch-builder2squash
  bin/ch-builder2tar
  bin/ch-dir2squash
  bin/ch-fromhost
  bin/ch-grow.py.in
  bin/ch-mount
  bin/ch-pull2dir
  bin/ch-pull2tar
  bin/ch-run-oci.py.in
  bin/ch-tar2dir
  bin/ch-test
  bin/ch-tug.py.in
  bin/ch-umount
  configure.ac
  doc/Makefile.am
  doc/conf.py
  lib/Makefile.am
  lib/base.sh
  lib/charliecloud.py
  misc/grep
  test/build.bats
  test/common.bash
  test/run/build-rpms.bats
  test/travis.yml
Labels: ready to merge?

#633 Make configure distinguish between "not present" and "too old"
  configure.ac
Labels: ready to merge?

#697 distribute Autoconf Archive macros we care about with Charliecloud
  configure.ac
  doc/install.rst
  misc/m4/README
  misc/m4/ax_check_compile_flag.m4
  misc/m4/ax_compare_version.m4
  misc/m4/ax_pthread.m4
  misc/m4/ax_with_prog.m4
  test/travis.bash
  test/travis.yml
Labels: enhancement, ready to merge?

#700 Vagrantfile: rm leftover PREFIX=
  packaging/vagrant/Vagrantfile
Labels: enhancement

#706 Travis: build in parallel
  test/travis.bash
Labels: ready to merge?

#679 move spark test artifacts to TMP_
  examples/spark/test.bats
Labels: ready to merge?

#704 ch-test: add --file and --file-tag
  bin/ch-test
  doc/ch-test_desc.rst
  examples/hello/test.bats
  examples/lammps/test.bats
  examples/lustre/test.bats
  examples/mpibench/test.bats
  examples/mpihello/test.bats
  examples/obspy/test.bats
  examples/paraview/test.bats
  examples/spack/test.bats
  examples/spark/test.bats
  test/Makefile.am
  test/build/10_sanity.bats
  test/build/50_ch-tug.bats
  test/build/50_dockerfile.bats
  test/build/50_misc.bats
  test/build/99_cleanup.bats
Labels: ready to merge?
