Repository hpc/charliecloud, pull requests merged in 2020-06, with the labels that each got.

#747 Ignore existing fixtures dir during install.
  test/Makefile.am
Labels: bug, ready to merge?

#761 ch-grow: execute instructions in order under Lark 0.8.6
  bin/ch-grow.py.in
Labels: bug

#763 ch-builder2tar: clean up builder checking
  bin/ch-builder2tar
Labels: bug

#746 document test suite dependency on ShellCheck
  configure.ac
  doc/install.rst
Labels: ready to merge?

#726 Tidy example images
  examples/.dockerignore
  examples/Dockerfile.centos6
  examples/Dockerfile.centos7
  examples/Dockerfile.centos8
  examples/Dockerfile.debian9
  examples/Dockerfile.mpich
  examples/Dockerfile.nvidia
  examples/Dockerfile.openmpi
  examples/Dockerfile.ubuntu1604
  examples/hello/Dockerfile
  examples/lammps/Dockerfile
  examples/mpibench/Dockerfile.mpich
  examples/mpibench/Dockerfile.openmpi
  examples/paraview/Dockerfile
  examples/spack/Dockerfile
  examples/spark/Dockerfile
Labels: ready to merge?

#762 dev_proc_sys.py: check /dev/cpu_dma_latency in addition to /dev/mem
  examples/chtest/dev_proc_sys.py
Labels: ready to merge?

#758 Update Vagrantfile
  packaging/vagrant/Vagrantfile
Labels: enhancement, ready to merge?

#772 ch-grow: document instruction support
  doc/ch-grow_desc.rst
  doc/faq.rst
Labels: ready to merge?
