Repository hpc/charliecloud, pull requests merged in 2021-09, with the labels that each got.

#1174 fix progress meter
  lib/charliecloud.py
Labels: bug, high, image

#1169 `ch-test --file`: match via substrings rather than exact
  bin/ch-test
  doc/ch-test_desc.rst
  test/common.bash
Labels: enhancement, medium, test, usability

#1117 `ch-run`: honor `$TMPDIR`
  bin/ch-run.c
  bin/ch_core.c
  bin/ch_misc.c
  bin/ch_misc.h
  doc/ch-run_desc.rst
  test/run/ch-run_misc.bats
Labels: enhancement, medium, runtime

#1181 `ch_misc.h`: mark `host_tmp` as extern to fix linking errors
  bin/ch_misc.h
Labels: bug, high, runtime
