Repository hpc/charliecloud, pull requests merged in 2021-01, with the labels that each got.

#942 docs: don’t claim we provide RPMs
  doc/install.rst
Labels: bug

#936 script to count lines of code
  .github/workflows/main.yml
  .gitmodules
  bin/Makefile.am
  misc/loc
Labels: enhancement

#921 configure: fix --with-sphinx-python
  configure.ac
Labels: bug, ready to merge?

#949 fix "sudo make install" with non-trivial umask
  .github/PERUSEME
  .github/workflows/main.yml
  configure.ac
  doc/Makefile.am
  test/Makefile.am
Labels: bug

#968 CI: fix Buildah
  bin/ch-build
Labels: ready to merge?

#963 examples: Paraview: change build type from debug to release
  examples/paraview/Dockerfile
Labels: enhancement

#966 ch-builder2tar: work for ch-image images containing slash
  bin/ch-build2dir
  bin/ch-builder2tar
  lib/base.sh
Labels: ready to merge?

#965 ch-image: strip setuid/setgid bits on pull too
  lib/charliecloud.py
  test/build/50_localregistry.bats
Labels: ready to merge?

#946 ch-fromhost: make Paraview tests work on CLE7
  bin/ch-fromhost
Labels: bug
