Repository hpc/charliecloud, pull requests merged in 2021-06, with the labels that each got.

#1104 document mailing list as read-only
  README.rst
Labels: doc, enhancement, medium

#1099 Add certificate verification error handling to FAQ
  doc/faq.rst
Labels: doc, enhancement, medium

#1110 fix bad assert syntax
  lib/build.py
Labels: bug, high, image

#1111 configure: remove bashism from SquashFUSE version check.
  configure.ac
Labels: bug, install, medium
