Repository hpc/charliecloud, pull requests merged in 2022-06, with the labels that each got.

#1378 point the participation link to Github repo
  README.rst
Labels: enhancement, low, doc

#1384 `ch-image`: crashes if requests is not installed, instead of proper error message
  lib/charliecloud.py
Labels: bug, medium, image

#1383 actually exclude non-amd64 for Arch Linux
  test/force-auto.py.in
Labels: bug, high, test
