Repository hpc/charliecloud, pull requests merged in 2023-01, with the labels that each got.

#1507 support storage directories up to 1 year old
  doc/ch-image.rst
  lib/filesystem.py
Labels: enhancement, medium, misc

#1538 configure: Remove bashisms, fix dash compatibility.
  configure.ac
Labels: bug, medium, install

#1544 fix tests
  bin/ch-run.c
  bin/ch_core.c
  bin/ch_misc.c
  bin/ch_misc.h
  test/build/50_ch-image.bats
  test/run/ch-run_misc.bats
Labels: bug, high, runtime, test

#1550 fix `realpath(3)` error handling
  bin/ch_misc.c
Labels: bug, high, runtime
