Repository hpc/charliecloud, pull requests merged in 2023-11, with the labels that each got.

#1735 `ch-convert`: add `--quiet`
  bin/ch-convert
  doc/ch-convert.rst
  lib/base.sh
  test/run/ch-convert.bats
Labels: enhancement, medium, misc

#1745 refactor `Path` to no longer subclass `pathlib.Path`
  bin/ch-run-oci.py.in
  lib/build.py
  lib/build_cache.py
  lib/charliecloud.py
  lib/filesystem.py
  lib/image.py
  lib/pull.py
  lib/push.py
  lib/registry.py
  test/doctest.py.in
Labels: refactor, medium, image

#1777 implement missed `Path.iterdir()`
  lib/filesystem.py
Labels: bug, high, image

#1781 disable Spack test
  examples/spack/Dockerfile
Labels: bug, high, test

#1782 don’t follow symlinks when setting xattrs
  lib/build_cache.py
  lib/filesystem.py
Labels: bug, medium, image

#1786 `lib/base.sh`: fix comment
  lib/base.sh
Labels: bug, low, doc
