Repository hpc/charliecloud, pull requests merged in 2023-05, with the labels that each got.

#1649 add mpich example improvements
  examples/Dockerfile.mpich
Labels: enhancement, medium, test

#1652 add completion for `ch-run`
  bin/ch-completion.bash
Labels: enhancement, medium, runtime

#1657 use relative symlink for skinny manifest
  lib/filesystem.py
  lib/pull.py
  test/build/55_cache.bats
Labels: bug, high, image

#1658 use different state ID for different imported image references
  doc/ch-image.rst
  lib/build.py
  lib/build_cache.py
  test/build/50_ch-image.bats
Labels: bug, high, image
