Repository hpc/charliecloud, pull requests merged in 2024-01, with the labels that each got.

#1793 add `--write-fake` via unprivileged overlayfs
  bin/ch-run.c
  bin/ch_core.c
  bin/ch_core.h
  bin/ch_fuse.c
  bin/ch_misc.c
  bin/ch_misc.h
  configure.ac
  doc/ch-run.rst
  doc/faq.rst
  doc/install.rst
  examples/chtest/Build
  packaging/fedora/build
  test/common.bash
  test/run/ch-run_misc.bats
  test/run_first.bats
Labels: enhancement, medium, runtime

#1800 fix wrong variable in error message
  bin/ch_misc.c
Labels: bug, medium, runtime

#1802 add `WARNING` to `base.sh`
  bin/ch-convert
  lib/base.sh
Labels: bug, medium, misc

#1804 add tab completion to `ch-convert`
  bin/ch-completion.bash
Labels: enhancement, medium, misc

#1808 block `mknod(2)` only if creating a device
  bin/ch_core.c
  doc/ch-image.rst
  doc/dev.rst
  examples/Makefile.am
  examples/paraview/Dockerfile
  examples/seccomp/Dockerfile
  examples/seccomp/mknods.c
  examples/seccomp/test.bats
  examples/spack/Dockerfile
Labels: bug, medium, runtime, image

#1792 update bundled Lark
  autogen.sh
  bin/ch-test
  doc/dev.rst
  lib/Makefile.am
  lib/build.py
  packaging/fedora/charliecloud.spec
  packaging/fedora/upstream.spec
Labels: enhancement, medium, image

#1815 fix scope handling
  bin/ch-test
  examples/seccomp/Dockerfile
  examples/spack/Dockerfile
Labels: bug, high, test

#1818 tidy tar-related output
  lib/charliecloud.py
  lib/image.py
Labels: bug, medium, image, doc, usability

#1825 add new log function for `printf(3)`-style debugging
  doc/dev.rst
  lib/charliecloud.py
Labels: enhancement, medium, image
